### PR TITLE
Do not perform full expansion of `#expect()` when `try` or `await` is present.

### LINKED ISSUE #783: `#expect` doesn't expect that there may be a sub-expression that has `try` on the right side of binary operator.
### Description

Although we can't put `try` on the right side of `==`, the right expression can contain a sub-expression that has `try`:

```swift
func nonThrowingFunc() -> Int { 0 }
func throwingFunc() throws -> Int { 0 }
func anotherNonThrowingFunc(_ integer: Int) -> Int { integer }

print(nonThrowingFunc() == try throwingFunc()) // ❌ error: 'try' cannot appear to the right of a non-assignment operator
print(nonThrowingFunc() == anotherNonThrowingFunc(try throwingFunc())) // ✅ OK
```

However, `#expect` seems not to expect that there may be a `try` sub-expression on the right side of `==`:

```swift
import Testing

struct Foo: Equatable {
  init() {}
  init(_ integer: Int) {}
}

@Test func myTest() throws {
  #expect(try #require(Int("0")) == 0) // ✅ OK
  #expect((Foo() == Foo(try #require(Int("0")))) == true) // ✅ OK
  #expect(Foo() == Foo(try #require(Int("0")))) // ❌ error: call can throw, but it is executed in a non-throwing autoclosure
}
```

Expanded function named `__checkBinaryOperation` doesn't have an `@autoclosure` that `throws`.

### Expected behavior

No error at compile time.

### Actual behavior

Described above.

### Steps to reproduce

Try to compile the code above.

### swift-testing version/commit hash

Testing Library Version: 94 (arm64e-apple-macos13.0)

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
Darwin yockow.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64

### PR DESCRIPTION
**Pull request by grynspan**
For reasons that have been documented at length (see #162), we aren't able to correctly expand conditions on `#expect()` or `#require()` that have effects (`try` or `await`.) We aren't currently detecting all possible patterns that expand incorrectly. This PR causes us to back out of the full expansion if the `try` or `await` keyword is present _anywhere_ inside an expectation condition expression.

Resolves #783.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci test

File: Sources/TestingMacros/Support/ConditionArgumentParsing.swift [hunk 1]
```diff
@@ -477,6 +466,22 @@ private func _parseCondition(negating expr: ExprSyntax, isParenthetical: Bool, f
 ///
 /// - Returns: An instance of ``Condition`` describing `expr`.
 private func _parseCondition(from expr: ExprSyntax, for macro: some FreestandingMacroExpansionSyntax, in context: some MacroExpansionContext) -> Condition {
+  // Handle closures with a single expression in them (e.g. { $0.foo() })
```
Comment (grynspan) [inline Sources/TestingMacros/Support/ConditionArgumentParsing.swift:469]: Moved this up so that closure "expansion" (not really but sure why not) still happens. If we ever actually start doing fun things with closures, we'll probably need to move this back down?

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test Windows

File: Tests/TestingTests/MiscellaneousTests.swift [hunk 2]
```diff
@@ -123,6 +123,15 @@ struct SendableTests: Sendable {
 
   @Test(.hidden, arguments: FixtureData.stringReturningClosureArray)
   func parameterizedAcceptingFunction(f: @Sendable () -> String) {}
+
+  @Test(.hidden) func throwKeywordInExpectation() throws {
```
Comment (briancroom) [inline Tests/TestingTests/MiscellaneousTests.swift:127]: These are test cases that would have failed compile prior to this fix?

Comment (grynspan) [reply Tests/TestingTests/MiscellaneousTests.swift:127]: Yep.

**Review by briancroom — APPROVED** [review]
