### PR TITLE
Disable inheritance of file descriptors created by Swift Testing by default.

### LINKED ISSUE #1140: Exit tests hang indefinitely on Ubuntu 20.04
### Description

When adding an exit test to a test suite, that test hangs indefinitely when run on Ubuntu 20.04. The test runs successfully and completes in ~0.3s on Ubuntu 22.04 and on all of the macOS versions that I've tried.

### Reproduction

1. Download the latest nightly-focal swift docker image
2. Create a project that includes the following unit test

```swift
@Test func testExits() {
    await #expect(processExitsWith: .failure) {
        fatalError("I crashed")
    }
}
```

3. Build and run the test (`swift test`)
4. Notice that the test hangs indefinitely after `◇ Test testExits() started.`

### Expected behavior

Exit tests complete successfully on all supported platforms

### Environment

```
↳ Testing Library Version: 6.3-dev (d6111205ce07f17)
↳ Target Platform: aarch64-unknown-linux-gnu
```

```
Swift version 6.2-dev (LLVM 5e7837820b1c886, Swift d5ef256b402bff7)
Target: aarch64-unknown-linux-gnu
Build config: +assertions
```

```
Linux nightly-focal 6.1.68 #1 SMP Fri Nov 22 18:05:17 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

### Additional information

This is blocking Foundation from adopting exit tests as swift toolchain CI runs on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by grynspan**
This PR makes file descriptors created by Swift Testing `FD_CLOEXEC` by default (on Windows, `~HANDLE_FLAG_INHERIT`.) We then clear `FD_CLOEXEC` for specific file descriptors that should be inherited. On Darwin, this is effectively ignored because we use `POSIX_SPAWN_CLOEXEC_DEFAULT`, and on Windows we use `PROC_THREAD_ATTRIBUTE_HANDLE_LIST` which has [much the same effect](https://devblogs.microsoft.com/oldnewthing/20111216-00/?p=8873). (On non-Darwin POSIX platforms, there's no reliable way to ensure only one child process inherits a particular file descriptor.)

This change is speculative. No additional unit tests are added because existing test coverage _should be_ sufficient; the reported issue is on a platform (Ubuntu 20.04) where we don't have any CI jobs.

Resolves #1140.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test

File: Sources/Testing/Support/FileHandle.swift [hunk 1]
```diff
@@ -553,6 +603,72 @@ extension FileHandle {
...
+  /// Set whether or not the given file descriptor is inherited by child processes.
+  ///
+  /// - Parameters:
+  /// 	- fd: The file descriptor.
+  ///   - inherited: Whether or not `fd` is inherited by child processes
+  ///   (ignoring overriding functionality such as Apple's
+  ///   `POSIX_SPAWN_CLOEXEC_DEFAULT` flag.)
+  ///
+  /// - Throws: Any error that occurred while setting the flag.
+  static func setFileDescriptorInherited(_ fd: CInt, _ inherited: Bool) throws {
```
Comment (stmontgomery) [inline Sources/Testing/Support/FileHandle.swift]: `(file)private`?

File: Sources/Testing/Support/FileHandle.swift [hunk 2]
```diff
@@ -553,6 +603,72 @@ extension FileHandle {
...
 #endif
+
+#if SWT_TARGET_OS_APPLE || os(Linux) || os(FreeBSD) || os(OpenBSD) || os(Android)
+  /// Set whether or not the given file descriptor is inherited by child processes.
+  ///
+  /// - Parameters:
+  /// 	- fd: The file descriptor.
+  ///   - inherited: Whether or not `fd` is inherited by child processes
+  ///   (ignoring overriding functionality such as Apple's
+  ///   `POSIX_SPAWN_CLOEXEC_DEFAULT` flag.)
```
Comment (stmontgomery) [inline Sources/Testing/Support/FileHandle.swift]: Nit: indentation

File: Sources/_TestingInternals/include/Stubs.h [hunk 3]
```diff
@@ -151,6 +151,27 @@ static int swt_EEXIST(void) {
...
+/// Call `fcntl(F_SETFD)`.
+///
+/// This function is provided because `fcntl()` is a variadic function and
+/// cannot be imported directly into Swift.
+static int swt_setfdflags(int fd, int flags) {
+  return fcntl(fd, F_SETFD, flags);
+}
+#endif
+
+
```
Comment (stmontgomery) [inline Sources/_TestingInternals/include/Stubs.h]: Nit: extra newline

File: Sources/Testing/Support/FileHandle.swift [hunk 4]
```diff
@@ -461,15 +489,37 @@ extension FileHandle {
...
+#endif
+
+      if !pipe2Called {
+        // pipe2() is not available. Use pipe() instead and simulate O_CLOEXEC
+        // to the best of our ability.
+        guard 0 == pipe(fds.baseAddress!) else {
+          throw CError(rawValue: swt_errno())
+        }
+        for fd in fds {
+          try? setFileDescriptorInherited(fd, false)
```
Comment (stmontgomery) [inline Sources/Testing/Support/FileHandle.swift]: Even though this is a fallback code path, should we propagate the error instead of using `try?`?

File: Sources/Testing/Support/FileHandle.swift (hunk 1 above)
Comment (grynspan) [reply Sources/Testing/Support/FileHandle.swift]: Yeah fair.

File: Sources/Testing/Support/FileHandle.swift (hunk 4 above)
Comment (grynspan) [reply Sources/Testing/Support/FileHandle.swift]: I considered it, but we have unmanaged resources in flight here (the file descriptors) and throwing from this point could leak them. In practice, this specific call cannot meaningfully fail anyway.

**Comment by jmschonfeld** [comment]
Confirmed that a swift-foundation branch with exit tests enabled successfully ran those exit tests with this swift-testing version on Ubuntu 20.04 (but failed previously)

File: Sources/Testing/Support/FileHandle.swift (hunk 4 above)
Comment (grynspan) [reply Sources/Testing/Support/FileHandle.swift]: Fixed with some code reorganization.

**Comment by grynspan** [comment]
@swift-ci test

**Review by stmontgomery — APPROVED** [review]

**Comment by stmontgomery** [comment]
@swift-ci Please test

**Comment by grynspan** [comment]
Relevant glibc change (non-portable and only on relatively recent glibc versions though.) https://sourceware.org/bugzilla/show_bug.cgi?id=23640

**Comment by grynspan** [comment]
FreeBSD also clears `FD_CLOEXEC` when you call `posix_spawn_file_actions_adddup2(n, n)` however I'll need to confirm what version implemented this functionality before I can rely on it.

**Comment by grynspan** [comment]
LOL 17 years ago. https://github.com/freebsd/freebsd-src/commit/947aa542e9b9539d4217d470ab7e3d1fe3b973a5#diff-270bf74296ff29076675e017c4ed6273a7f19fe97a89a27e2fc4a2beda6bbb43R160

**Comment by grynspan** [comment]
And OpenBSD too: https://github.com/openbsd/src/blob/master/lib/libc/gen/posix_spawn.c#L155

**Comment by grynspan** [comment]
And Android: https://android.googlesource.com/platform/bionic/+/master/libc/bionic/spawn.cpp#103
