### PR TITLE
Fix a crash when describing a confirmation failure with a range.

### LINKED ISSUE #805: Crash when a call to `confirmation(expectedCount: 1...) { ... }` fails
### Description

I'm seeing a crash during issue stringification when running a test which fails due to a particular range-based confirmation failing.

### Expected behavior

Expected an ordinary test failure, not a crash.

### Actual behavior

A crash is occurring inside `Issue.Kind.description.getter`, specifically, at `Issue.swift:203` in my checkout.

### Steps to reproduce

Run the following test:

```
@Test func confirmedTooFewTimes() async {
  await confirmation(expectedCount: 1...) { (thingHappened) async in }
}
```

### swift-testing version/commit hash

759ce021552dc3939255f4cede093605404b58a8

### Swift & OS version (output of `swift --version ; uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by grynspan**
I was using `relative(to:)` to convert any arbitrary `RangeExpression` to one with an upper and lower bound, but that function may produce invalid ranges for expressions like `1...` that cause crashes.

This PR switches to a different, somewhat sillier implementation that should not run into this issue.

Resolves #805.
Resolves rdar://139222774.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci test

**Review by stmontgomery — APPROVED** [review]

File: Sources/Testing/Issues/Issue.swift [hunk 1]
```diff
@@ -175,11 +175,9 @@ extension Issue: CustomStringConvertible, CustomDebugStringConvertible {
 /// In the future, when our minimum deployment target supports casting a value
 /// to a constrained existential type ([SE-0353](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0353-constrained-existential-types.md#effect-on-abi-stability)),
 /// we can remove this protocol and cast to `RangeExpression<Int>` instead.
-private protocol _RangeExpressionOverIntValues: RangeExpression where Bound == Int {}
+private protocol _RangeExpressionOverIntValues: RangeExpression & Sequence where Bound == Int, Element == Int {}
```
Comment (stmontgomery) [inline Sources/Testing/Issues/Issue.swift:178]: Would it be stronger / more precise to constrain such that `Element == Bound`?
```suggestion
private protocol _RangeExpressionOverIntValues: RangeExpression & Sequence where Bound == Int, Element == Bound {}
```

**Review by briancroom — APPROVED** [review]
