### PR TITLE
Show the number of test cases that ran at the end of a test

### LINKED ISSUE #943: Log the number of test cases run when a test function finishes
### Description

Given test logs can easily get burried, the final test logs printed are significant to understand how well a test ran.

TLDR;
- Currently: it's not clear from the final statement how many arguments were tested
- Desired: I suggest below some extra logs to better understand the total arguments tested:

### Desired
```
􀟈 Test aPileBringsHuggers(moveFn:) started.
􀟈 Passing 1 argument moveFn → (Function) to aPileBringsHuggers(moveFn:)
// ...
​􁁛 Argument in aPileBringsHuggers(moveFn:) passed after 2 seconds. 🆕
​􀟈 Passing 1 argument moveFn → (Function) to aPileBringsHuggers(moveFn:)
// ...
​􁁛 Argument in aPileBringsHuggers(moveFn:) passed after 2 seconds. 🆕
​􁁛 Test aPileBringsHuggers(moveFn:) with 2 arguments passed after 4.677 seconds. 🆕
```

Here above, I suggested the lines marked as 🆕
1. an extra log after each argument passes or fails, and
2. a total amount of arguments tested to the final log.

### Currently (example with 2 arguments tested)
```
􀟈 Test aPileBringsHuggers(moveFn:) started.
􀟈 Passing 1 argument moveFn → (Function) to aPileBringsHuggers(moveFn:)
// ...
​􀟈 Passing 1 argument moveFn → (Function) to aPileBringsHuggers(moveFn:)
// ...
​􁁛 Test aPileBringsHuggers(moveFn:) passed after 4.677 seconds.
```
Given that these logs easily get buried, I think something like the above would be way better.

### Steps to reproduce

Write a swift test with arguments and run it.

Relevant thread:
https://forums.swift.org/t/fr-test-with-arguments-and-closures-dx-suggestions-to-clarify-all-arguments-were-tested/77677/7

### swift-testing version/commit hash

not sure how to check

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.115.1 Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
Target: arm64-apple-macosx15.0
Darwin Dendrocopus.local 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 19:02:41 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6030 arm64

### PR DESCRIPTION
**Pull request by hrayatnia**
### Motivation:

To have the number of test cases at the end of the test in for parameterized tests, so the logs don’t easily get buried.

### Modifications:

Log the number of test cases for parameterized tests at the end of a test.

### Result:

If the user runs the parameterized tests, an extra piece of information (with * test cases) would get bound to the end log.

Resolves #943.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 1]
```diff
@@ -147,31 +147,18 @@ extension Event.HumanReadableOutputRecorder {
...
-  /// - Returns: A string describing the number of arguments in the test cases, or an empty string if it's not very verbose level.
+  /// - Returns: A string describing the number of argument(s) in the test cases, or an empty string if it's not very verbose level.
   ///
-  private func _includeNumberOfArguments(_ test: Test, verbose: Int) -> String {
-      if verbose == 2 { // very verbose
-          let numberOfArguments = _numberOfArguments(for: test.testCases)
-          return " with \(numberOfArguments) " + (numberOfArguments > 1 ? "arguments" : "argument")
+  private func _includeNumberOfTestCases(for test: Test, verbose: Int) -> String {
+    if verbose == 2 && !test.isSuite { // very verbose
+        let testCasesCount =  test.testCases?.count(where: { _ in true }) ?? 0
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:160]: Calling `testCases` here will produce a second sequence of test cases, which makes getting the number of test cases an O(_n_) operation instead of O(1). What we would normally do is keep a running count of test cases in the `TestData` structure, incrementing it for each `.testCaseStarted` event.

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 2]
```diff
@@ -147,31 +147,18 @@ extension Event.HumanReadableOutputRecorder {
...
   ///
-  /// - Returns: A string describing the number of arguments in the test cases, or an empty string if it's not very verbose level.
+  /// - Returns: A string describing the number of argument(s) in the test cases, or an empty string if it's not very verbose level.
   ///
-  private func _includeNumberOfArguments(_ test: Test, verbose: Int) -> String {
-      if verbose == 2 { // very verbose
-          let numberOfArguments = _numberOfArguments(for: test.testCases)
-          return " with \(numberOfArguments) " + (numberOfArguments > 1 ? "arguments" : "argument")
+  private func _includeNumberOfTestCases(for test: Test, verbose: Int) -> String {
+    if verbose == 2 && !test.isSuite { // very verbose
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:159]: You probably mean `>= 2`, right?

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 3]
```diff
@@ -147,31 +147,18 @@ extension Event.HumanReadableOutputRecorder {
...
+        let testCasesCount =  test.testCases?.count(where: { _ in true }) ?? 0
+        return " with \(testCasesCount) " + (testCasesCount > 1 ? "test cases" : "test case")
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift]: We have a helper function for pluralizing English nouns (used elsewhere in this file.)

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 4]
```diff
@@ -147,31 +147,18 @@ extension Event.HumanReadableOutputRecorder {
...
-
   /// Returns a formatted string describing the number of arguments in a test, based on verbosity level.
   ///
   /// - Parameters:
-  ///   - test: The `Test` object that contains a sequence of `testCases`.
+  ///   - test: to get the number of  `testCases` out of a ``Test``.
   ///   - verbose: If the level is very verbose, a detailed description is returned.
   ///
-  /// - Returns: A string describing the number of arguments in the test cases, or an empty string if it's not very verbose level.
+  /// - Returns: A string describing the number of argument(s) in the test cases, or an empty string if it's not very verbose level.
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift]: Documentation comments (but not code) should wrap at 80 columns. This helps give readers a sense of how long the documentation will be when rendered with DocC.

**Review by grynspan — CHANGES_REQUESTED** [review]
Thanks for opening this PR! It would be a good idea to familiarize yourself with the existing code in `Event.HumanReadableOutputRecorder.swift` and get a feel for how it works and the existing mechanisms we use for gathering data during test runs.

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift (hunk 2 above)
Comment (hrayatnia) [reply Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift]: updated

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift (hunk 3 above)
Comment (hrayatnia) [reply Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift]: thanks, applied. 🙏

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift (hunk 4 above)
Comment (hrayatnia) [reply Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift]: Applied, sorry for not double-checking it.

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift (hunk 1 above)
Comment (hrayatnia) [reply Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift]: Thank you, it helps me understand the way you guys think 🙏.

Honestly, it was my first idea; however, I thought it is the same due to the fact that O(n) gets distributed among each test run and also adds a negligible amount of miscalculation to the compute time (because it happens after the start instant as well as it adds 8 bytes of additional data to the test data). For those reasons, I went with the second solution.

I fixed the issue.

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 5]
```diff
@@ -281,6 +307,18 @@ extension Event.HumanReadableOutputRecorder {
           testData.issueCount[issue.severity] = issueCount + 1
         }
         context.testData[id] = testData
+      
+      case .testCaseStarted:
+        guard verbosity >= 2 else { break }
+        let id: [String] = if let test {
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:313]: We don't check verbosity in this first `switch` intentionally so that the data we collect is always comprehensive. The second `switch` below checks verbosity before producing any messages.

`test` will never be `nil` for this event, and `.testStarted` will always be recorded before `.testCaseStarted`, so you can just write:

```swift
case .testCaseStarted:
  let test = test!
  context.testData[test.id.keyPathRepresentation]?.testCasesCount += 1
```

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 6]
```diff
@@ -146,6 +149,29 @@ extension Event.HumanReadableOutputRecorder {
...
+  ///   - isParameterized: To check test cases count should be included.
+  ///   - count: The number of test cases in the test.
+  ///   - verbosity: The verbosity level. If it's very verbose or higher,
+  ///     the test cases count might get included.
+  ///
+  ///
+  /// - Returns: A string describing the number of test cases in the test,
+  ///   or an empty string if it's not very verbose level.
+  ///
+  private func _includeNumberOfTestCasesIfNeeded(
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:166]: You probably don't need this helper function and can just construct the string in place in the `.testEnded` handler below.

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 7]
```diff
@@ -366,18 +404,21 @@ extension Event.HumanReadableOutputRecorder {
       let testData = testDataGraph?.value ?? .init(startInstant: instant)
       let issues = _issueCounts(in: testDataGraph)
       let duration = testData.startInstant.descriptionOfDuration(to: instant)
+      let testCasesCountMessage = _includeNumberOfTestCasesIfNeeded(test.isParameterized,
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:407]: Here, you can probably just write:

```swift
let testCasesCount = if verbosity >= 2 && test.isParameterized {
  " with \(testData.testCasesCount.counting("test case"))"
} else {
  ""
}
```

("Message" has a domain-specific meaning in this file, which is why I renamed this variable in my example above.)

**Comment by grynspan** [comment]
Please update the PR description to explain what this PR does so that we can refer back to it in the future. (You don't need to use the full template for new PRs if you don't need it, but it can be helpful to structure the PR description.)

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift (hunk 4 above)
Comment (stmontgomery) [reply Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift]: For more details see the [Style Guide](https://github.com/swiftlang/swift-testing/blob/main/Documentation/StyleGuide.md).

**Comment by hrayatnia** [comment]
@grynspan Thank you for being patience with me. I've applied all the requested changes—please review and resolve if everything looks good. Also, I'll make an effort to participate more in code reviews and go through other pull requests to minimize trivial questions in the future.

@stmontgomery Thank you for your support as well. 🙏

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 8]
```diff
@@ -146,6 +149,7 @@ extension Event.HumanReadableOutputRecorder {
 
     return (errorIssueCount, warningIssueCount, knownIssueCount, totalIssueCount,  description)
   }
+
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:152]: Nitpick: stray newline? :)

File: Tests/TestingTests/EventRecorderTests.swift [hunk 9]
```diff
@@ -566,3 +610,4 @@ struct EventRecorderTests {
     }
   }
 }
+
```
Comment (grynspan) [inline Tests/TestingTests/EventRecorderTests.swift:613]: Nitpick: stray newline?

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 10]
```diff
@@ -366,18 +373,23 @@ extension Event.HumanReadableOutputRecorder {
       let testData = testDataGraph?.value ?? .init(startInstant: instant)
       let issues = _issueCounts(in: testDataGraph)
       let duration = testData.startInstant.descriptionOfDuration(to: instant)
+      let testCasesCount = if verbosity >= 2 && test.isParameterized {
```
Comment (grynspan) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:376]: @stmontgomery What do you think about the required verbosity here?

File: Tests/TestingTests/EventRecorderTests.swift [hunk 11]
```diff
@@ -178,6 +178,44 @@ struct EventRecorderTests {
...
+  
+  @available(_regexAPI, *)
+  @Test(
+    "number of arguments based on verbosity level at the end of test run",
+    arguments: [
+      ("f()", #".* Test f\(\) failed after .*"# ,  0),
+      ("f()", #".* Test f\(\) failed after .*"# ,  2),
+      ("d(_:)", #".* Test d\(_:\) with .+ test cases passed after.*"# , 2),
+      ("PredictablyFailingTests", #".* Suite PredictablyFailingTests failed after .*"# , 1),
+      ("PredictablyFailingTests", #".* Suite PredictablyFailingTests failed after .*"# , 2),
```
Comment (stmontgomery) [inline Tests/TestingTests/EventRecorderTests.swift:190]: nit: whitespace
```suggestion
      ("f()", #".* Test f\(\) failed after .*"#, 0),
      ("f()", #".* Test f\(\) failed after .*"#, 2),
      ("d(_:)", #".* Test d\(_:\) with .+ test cases passed after.*"#, 2),
      ("PredictablyFailingTests", #".* Suite PredictablyFailingTests failed after .*"#, 1),
      ("PredictablyFailingTests", #".* Suite PredictablyFailingTests failed after .*"#, 2),
```

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 12]
```diff
@@ -62,6 +62,9 @@ extension Event {
 
         /// The number of known issues recorded for the test.
         var knownIssueCount = 0
+        
+        /// The number of test cases for the test.
+        var testCasesCount: Int = 0
```
Comment (stmontgomery) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:67]: nit: can omit the explicit type since this isn't a `public` property, to match prevailing style
```suggestion
        var testCasesCount = 0
```

**Comment by stmontgomery** [comment]
@swift-ci please test

File: Tests/TestingTests/EventRecorderTests.swift [hunk 13]
```diff
@@ -178,6 +178,44 @@ struct EventRecorderTests {
         .first != nil
     )
   }
+  
+  @available(_regexAPI, *)
+  @Test(
+    "number of arguments based on verbosity level at the end of test run",
```
Comment (stmontgomery) [inline Tests/TestingTests/EventRecorderTests.swift:184]: The display name of this test can be rephrased now to not mention verbosity. I'd also prefer if we could capitalize the first word to match prevailing style.

**Review by stmontgomery — APPROVED** [review]
Couple more style comments but besides that I think this is ready to land. Thanks @hrayatnia!

**Review by grynspan — APPROVED** [review]

**Comment by stmontgomery** [comment]
@swift-ci please test
